### ISSUE TITLE
Incorrect image used in blog post

### ISSUE THREAD

**Issue by karbassi** [ChillarAnand/avilpage.com#12]
Hey @ChillarAnand,

I can't seem to find your blog post source on github, so I can't submit a PR, however, on:

https://avilpage.com/2020/10/python-docker-build-slim-fast.html
https://github.com/ChillarAnand/avilpage.com/blob/gh-pages/2020/10/python-docker-build-slim-fast.md

The last image should be `/images/docker5.png` not `/images/docker4.png`

**Comment by ChillarAnand** [comment]
@karbassi Thanks for noticing the issue and raising an issue for that. 

Looks like that post was not pushed to Github. I have updated it and pushed a fix for that.
