### ISSUE TITLE
Betamax vs requests_cache

### ISSUE THREAD

**Issue by sdementen** [ChillarAnand/avilpage.com#9]
For a better control, you can use betamax to record and replay API calls.
Betamax also allows to avoid storing passwords/API keys/...

**Comment by ChillarAnand** [comment]
@sdementen  Thank you for suggesting betamax. It also seems to have [integration with pytest](https://betamax.readthedocs.io/en/latest/integrations.html). Will try it out.

**Comment by sdementen** [comment]
Learning curve a bit higher than requests_cache but is worth the investment.
But requests_cache is nice when using an API in a script and not wanting to trigger a real call when in development/iteration mode (because slow, expensive, hitting a quota,...)

**Comment by ChillarAnand** [comment]
Thanks, @sdementen
